// export const onRenderBody = ({ setHeadComponents }) => {
//     setHeadComponents([
//       <link
//         rel="preload"
//         href="/fonts/Figtree-Light.woff2"
//         as="font"
//         type="font/woff2"
//         crossOrigin="anonymous"
//         key="figtreeFont"
//       />,
//       <link
//         rel="preload"
//         href="/fonts/Figtree-Regular.woff2"
//         as="font"
//         type="font/woff2"
//         crossOrigin="anonymous"
//         key="figtreeFont"
//       />,
//       <link
//         rel="preload"
//         href="/fonts/Figtree-Medium.woff2"
//         as="font"
//         type="font/woff2"
//         crossOrigin="anonymous"
//         key="figtreeFont"
//       />,
//       <link
//         rel="preload"
//         href="/fonts/Figtree-Bold.woff2"
//         as="font"
//         type="font/woff2"
//         crossOrigin="anonymous"
//         key="figtreeFont"
//       />,
//       <link
//         rel="preload"
//         href="/fonts/Figtree-ExtraBold.woff2"
//         as="font"
//         type="font/woff2"
//         crossOrigin="anonymous"
//         key="figtreeFont"
//       />,
//       <link
//         rel="preload"
//         href="/fonts/Figtree-Black.woff2"
//         as="font"
//         type="font/woff2"
//         crossOrigin="anonymous"
//         key="figtreeFont"
//       />,
//     ])
//   }